---
stages:
  - build
  - release

build_job:
  stage: build
  image: php:8.1
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - apt-get update -y
    - apt-get install -y git unzip libgmp3-dev
    - docker-php-ext-install pdo_mysql gmp
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install --no-dev --optimize-autoloader
    - tar czf moon-mining-manager-$CI_COMMIT_TAG.tar.gz
        app/
        bootstrap/
        config/
        database/
        public/
        resources/
        routes/
        storage/
        vendor/
        .env.example
        LICENSE
        README.md
        artisan
        composer.json
        composer.lock
        package-lock.json
        package.json
    - echo "BUILD_JOB_ID=$CI_JOB_ID" > build.env
  artifacts:
    name: 'moon-mining-manager-$CI_COMMIT_TAG'
    paths:
      - 'moon-mining-manager-$CI_COMMIT_TAG.tar.gz'
    expire_in: never
    reports:
      dotenv: build.env

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: build_job
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Create release."
  release:
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'
    assets:
      links:
        - name: 'moon-mining-manager-$CI_COMMIT_TAG.tar.gz'
          url: '$CI_SERVER_URL/$CI_PROJECT_PATH/-/jobs/$BUILD_JOB_ID/artifacts/download'

