version: '3'

services:
  moon_php:
    build:
      context: config
      dockerfile: dockerfile-php
    depends_on: [moon_db]
    volumes: [.:/app]
    working_dir: /app

  moon_node:
    image: node:16-alpine
    volumes: [.:/app]
    working_dir: /app
    tty: true

  moon_http:
    image: nginx:1
    depends_on: [moon_php]
    volumes: [.:/app, ./config/docker-nginx.conf:/etc/nginx/conf.d/default.conf]
    ports: ['8000:80']

  moon_db:
    image: mariadb:10.5
    ports: ['3307:3306']
    volumes: [./db:/var/lib/mysql]
    environment:
      MYSQL_DATABASE: moon_mining_manager
      MYSQL_USER: moon_mining_manager
      MYSQL_PASSWORD: moon
      MYSQL_ROOT_PASSWORD: moon
